//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.28 at 05:30:35 PM EEST 
//


package gun;

import comparators.GunComparator;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;


/**
 * <p>Java class for Gun complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Gun">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Model" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Handy" type="{http://viktorkaramba.com.laboratory_2/gun}Handy"/>
 *         &lt;element name="Origin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TTC">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Range" type="{http://viktorkaramba.com.laboratory_2/gun}Range"/>
 *                   &lt;element name="SightingRange" type="{http://viktorkaramba.com.laboratory_2/gun}SightingRange"/>
 *                   &lt;element name="PresenceOfClip" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="AvailabilityOfOptics" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Material" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Gun", propOrder = {
    "model",
    "handy",
    "origin",
    "ttc",
    "material"
})
public class Gun{
    @XmlElement(name = "Model", required = true)
    protected String model;
    @XmlElement(name = "Handy", required = true)
    protected Handy handy;
    @XmlElement(name = "Origin", required = true)
    protected String origin;
    @XmlElement(name = "TTC", required = true)
    protected TTC ttc;
    @XmlElement(name = "Material", required = true)
    protected String material;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    @Override
    public String toString(){
        return "    Gun{" +
                "Model='" + model + '\'' +
                ", Handy='" + handy + '\'' +
                ", Origin=" + origin +
                ",\n        TTC=" + ttc +
                "   , material=" + material +
                ", id=" + id +
                '}';
    }
    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the handy property.
     * 
     * @return
     *     possible object is
     *     {@link Handy }
     *     
     */
    public Handy getHandy() {
        return handy;
    }

    /**
     * Sets the value of the handy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Handy }
     *     
     */
    public void setHandy(Handy value) {
        this.handy = value;
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigin(String value) {
        this.origin = value;
    }

    /**
     * Gets the value of the ttc property.
     * 
     * @return
     *     possible object is
     *     {@link TTC }
     *     
     */
    public TTC getTTC() {
        return ttc;
    }

    /**
     * Sets the value of the ttc property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTC }
     *     
     */
    public void setTTC(TTC value) {
        this.ttc = value;
    }

    /**
     * Gets the value of the material property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterial() {
        return material;
    }

    /**
     * Sets the value of the material property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterial(String value) {
        this.material = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }



    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Range" type="{http://viktorkaramba.com.laboratory_2/gun}Range"/>
     *         &lt;element name="SightingRange" type="{http://viktorkaramba.com.laboratory_2/gun}SightingRange"/>
     *         &lt;element name="PresenceOfClip" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="AvailabilityOfOptics" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "range",
        "sightingRange",
        "presenceOfClip",
        "availabilityOfOptics"
    })
    public static class TTC{

        @XmlElement(name = "Range", required = true)
        protected Range range;
        @XmlElement(name = "SightingRange", required = true)
        protected BigDecimal sightingRange;
        @XmlElement(name = "PresenceOfClip")
        protected boolean presenceOfClip;
        @XmlElement(name = "AvailabilityOfOptics")
        protected boolean availabilityOfOptics;

        @Override
        public String toString() {
            return "TTC{" +
                    "Range='" + range + '\'' +
                    ", Sighting Range='" + sightingRange + '\'' +
                    ", PresenceOfClip=" + presenceOfClip +
                    ", AvailabilityOfOptics=" + availabilityOfOptics +
                    '}' + "\n";
        }
        /**
         * Gets the value of the range property.
         * 
         * @return
         *     possible object is
         *     {@link Range }
         *     
         */
        public Range getRange() {
            return range;
        }

        /**
         * Sets the value of the range property.
         * 
         * @param value
         *     allowed object is
         *     {@link Range }
         *     
         */
        public void setRange(Range value) {
            this.range = value;
        }

        /**
         * Gets the value of the sightingRange property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getSightingRange() {
            return sightingRange;
        }

        /**
         * Sets the value of the sightingRange property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setSightingRange(BigDecimal value) {
            this.sightingRange = value;
        }

        /**
         * Gets the value of the presenceOfClip property.
         * 
         */
        public boolean isPresenceOfClip() {
            return presenceOfClip;
        }

        /**
         * Sets the value of the presenceOfClip property.
         * 
         */
        public void setPresenceOfClip(boolean value) {
            this.presenceOfClip = value;
        }

        /**
         * Gets the value of the availabilityOfOptics property.
         * 
         */
        public boolean isAvailabilityOfOptics() {
            return availabilityOfOptics;
        }

        /**
         * Sets the value of the availabilityOfOptics property.
         * 
         */
        public void setAvailabilityOfOptics(boolean value) {
            this.availabilityOfOptics = value;
        }

    }
}
